server:
  port: 0

springdoc:
  api-docs:
    path: /mascota-service/api-docs

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/ 

spring:
  application:
    name: mascota-service
  flyway:
    enabled: 'true'
    baseline-on-migrate: 'true'
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: 'true'

  profiles:
    active: dev 
---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    username: root
    url: jdbc:mysql://localhost:3306/mascota_db?createDatabaseIfNotExist=true
    driverClassName: com.mysql.cj.jdbc.Driver
    password: ''
  jpa:
    hibernate:
      ddl-auto: update # Permitimos que actualice localmente si es necesario
