server:
  port: 8080

spring:
  application:
    name: gateway
  cloud:
    gateway:
      server:
        webmvc:
          globalcors:
            cors-configurations:
              '[/**]':
                allowed-origin-patterns: "*"
                allowed-methods: "*"
                allowed-headers: "*"
                exposed-headers: "*"
                allow-credentials: false
                max-age: 3600

          routes:
              - id: mascota-service
                uri:  lb://mascota-service
                predicates:
                  - Path=/api/v1/mascota/** 
                    , /api/v1/tipomascota/**
                    , /api/v1/estado/**
                    , /api/v1/mascota/buscar-pet/** 
                    , /api/v2/mascota/**
                    , /api/v2/tipomascota/**
                    , /api/v2/estado/**
                    , /mascota-service/api-docs/**
                
              - id: usuario-service
                uri: lb://usuario-service
                predicates:
                  - Path=/api/v1/usuario/**
                    , /api/v2/usuario/**
                    , /usuario-service/api-docs/**

              - id: inventario-service
                uri: lb://inventario-service
                predicates:
                  - Path=/api/v1/inventario/**
                   , /api/v1/item/**
                   , /api/v1/inventario/save-inventario
                   , /api/v1/inventario/update-inventario
                   , /api/v2/inventario/**
                   , /api/v2/item/**
                   , /inventario-service/api-docs/**

              - id: tienda-service
                uri: lb://tienda-service
                predicates:
                  - Path=/api/v1/tienda/**
                    , /api/v2/tienda/**
                    , /api/v1/tiendaItem/**
                    , /api/v2/tiendaItem/**
                    , /tienda-service/api-docs/**

              - id: accion-service
                uri: lb://accion-service
                predicates:
                  - Path=/api/v1/accion/** 
                    , /api/v1/historial/mascota/**
                    , /api/v2/accion/**
                    , /api/v2/historial/**
                    , /accion-service/api-docs/**


springdoc:
  swagger-ui:
    path: /swagger-ui/index.html
    urls:
      - name: Microservicio mascota-service
        url: /mascota-service/api-docs

      - name: Microservicio usuario-service
        url: /usuario-service/api-docs
        
      - name: Microservicio inventario-service
        url: /inventario-service/api-docs

      - name: Microservicio accion-service
        url: /accion-service/api-docs

      - name: Microservicio tienda-service
        url: /tienda-service/api-docs
    disable-swagger-default-url: true
    display-request-duration: true
  api-docs:
    enabled: true

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE:http://localhost:8761/eureka/}
  instance:
    prefer-ip-address: false
